
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]


live_config_reload = true


[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity = 0.85

[font]
size = 9.0

[font.bold]
#family = "ProggyCleanSZ Nerd Font Mono"
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
#family = "ProggyCleanSZ Nerd Font Mono"
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
#family = "ProggyCleanSZ Nerd Font Mono"
family = "MesloLGS Nerd Font Mono"
style = "Regular Italic"


[font.normal]
#family = "ProggyCleanSZ Nerd Font Mono"
family = "MesloLGS Nerd Font Mono"
style = "Regular"

